import { SiteTemplate } from './types';

/**
 * Logic to transform raw Agent output into a usable SiteTemplate.
 * This ensures the AI's creativity aligns with our strict Block schemas.
 */
export const generateSiteFromAgentResponse = (agentData: any): SiteTemplate => {
    // 1. Extract Core Intent
    const siteType = agentData.siteType || 'custom';
    const pageTitle = agentData.pageTitle || 'New Project';
    
    // 2. Map Blocks
    // The agent might return simplified block definitions (e.g. "hero").
    // We need to hydrate them with defaults if data is missing.
    const blocks = (agentData.blocks || []).map((b: any, i: number) => ({
        blockId: `ai-gen-block-${i}`,
        type: b.type,
        order: i,
        data: {
            ...b.data,
            // Add smart defaults here if needed
            // e.g. if type is 'hero' and no image, fetch from scraper (handled in builder page)
        }
    }));

    // 3. Construct Template
    return {
        id: `ai-template-${Date.now()}`,
        name: pageTitle,
        siteType: 'custom',
        description: 'Generated by EntreSite AI',
        pages: [{
            id: 'home',
            title: 'Home',
            blocks: blocks,
            canonicalListings: [],
            brochureUrl: "",
            seo: {
                title: pageTitle,
                description: `Welcome to ${pageTitle}`,
                keywords: []
            },
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        }]
    };
}
