export const COUNTRY_CODES = [
  { code: '+971', label: '🇦🇪 UAE' },
  { code: '+966', label: '🇸🇦 KSA' },
  { code: '+20', label: '🇪🇬 Egypt' },
  { code: '+1', label: '🇺🇸 USA' },
  { code: '+44', label: '🇬🇧 UK' },
  { code: '+974', label: '🇶🇦 Qatar' },
  { code: '+973', label: '🇧🇭 Bahrain' },
  { code: '+965', label: '🇰🇼 Kuwait' },
  { code: '+968', label: '🇴🇲 Oman' },
  { code: '+962', label: '🇯🇴 Jordan' },
  { code: '+961', label: '🇱🇧 Lebanon' },
  { code: '+972', label: '🇮🇶 Iraq' },
  { code: '+964', label: '🇸🇾 Syria' },
  { code: '+213', label: '🇩🇿 Algeria' },
  { code: '+216', label: '🇹🇳 Tunisia' },
  { code: '+212', label: '🇲🇦 Morocco' },
  { code: '+218', label: '🇱🇾 Libya' },
 { code: '+218', label: '🇱🇾 Libya' },
  { code: '+249', label: '🇸🇩 Sudan' },
    { code: '+967', label: '🇾🇪 Yemen' },
    { code: '+253', label: '🇩🇯 Djibouti' },
    { code: '+254', label: '🇰🇪 Kenya' },
    { code: '+255', label: '🇹🇿 Tanzania' },
    { code: '+256', label: '🇺🇬 Uganda' },
    { code: '+257', label: '🇧🇮 Burundi' },
    { code: '+260', label: '🇿🇲 Zambia' },
    { code: '+263', label: '🇿🇼 Zimbabwe' },
    { code: '+264', label: '🇲🇼 Malawi' },
    { code: '+265', label: '🇳🇦 Namibia' },
    { code: '+266', label: '🇸🇹 Sierra Leone' },
    { code: '+267', label: '🇧🇼 Botswana' },
    { code: '+268', label: '🇨🇭 Switzerland' },
    { code: '+269', label: '🇰🇲 Comoros' },
    { code: '+27', label: '🇿🇦 South Africa' },
 { code: '+62', label: '🇮🇩 Indonesia' },
   { code: '+63', label: '🇵🇭 Philippines' },
     { code: '+64', label: '🇦🇺 Australia' },
     { code: '+65', label: '🇸🇬 Singapore' },
      { code: '+66', label: '🇹🇭 Thailand' },
       { code: '+84', label: '🇻🇳 Vietnam' },
       { code: '+850', label: '🇰🇭 Cambodia' },
       { code: '+852', label: '🇭🇰 Hong Kong' },
       { code: '+853', label: '🇲🇴 Macau' },
         { code: '+855', label: '🇱🇦 Laos' },
         { code: '+856', label: '🇲🇲 Myanmar' },
         { code: '+886', label: '🇹🇼 Taiwan' },
         { code: '+90', label: '🇹🇷 Turkey' },
         { code: '+91', label: '🇮🇳 India' },
         { code: '+92', label: '🇵🇰 Pakistan' },
            { code: '+93', label: '🇦🇫 Afghanistan' },
            { code: '+94', label: '🇱🇰 Sri Lanka' },
            { code: '+95', label: '🇲🇲 Myanmar' },
            { code: '+98', label: '🇮🇷 Iran' },
                   
];