import 'dotenv/config';
import assert from 'node:assert/strict';
import { getApps, initializeApp, applicationDefault } from 'firebase-admin/app';
import { getFirestore, FieldValue } from 'firebase-admin/firestore';

type RefinerStep = {
  name: 'analyzeStructure' | 'applyRefinements' | 'finalReview';
  result: string;
};

const STEPS: RefinerStep[] = [
  { name: 'analyzeStructure', result: 'Structure validated for refiner pass' },
  { name: 'applyRefinements', result: 'Applied typography + spacing polish' },
  { name: 'finalReview', result: 'Draft approved for review' },
];

const SMOKE_TENANT_ID = process.env.SMOKE_TENANT_ID || 'smoke-refiner-tenant';
const OWNER_UID = process.env.SMOKE_OWNER_UID || SMOKE_TENANT_ID;

function initAdmin() {
  if (!getApps().length) {
    initializeApp({
      credential: applicationDefault(),
    });
  }
}

async function queueRefinerJob() {
  const db = getFirestore();
  const siteId = `smoke-refiner-${Date.now()}`;
  const jobTitle = 'Smoke Refiner Landing Page';

  const page = {
    id: siteId,
    title: jobTitle,
    blocks: [
      {
        blockId: `hero-${Date.now()}`,
        type: 'hero',
        order: 0,
        data: {
          eyebrow: 'Smoke Suite',
          headline: 'AI-polished builder smoke test',
          description: 'Ensures Refiner jobs propagate across dashboards.',
          primaryCtaLabel: 'Inspect Draft',
        },
      },
    ],
    canonicalListings: [],
    brochureUrl: '',
    tenantId: OWNER_UID,
    ownerUid: OWNER_UID,
    seo: {
      title: 'Smoke Refiner',
      description: 'Smoke test page for Refiner jobs',
      keywords: ['smoke', 'refiner'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  await db.collection('sites').doc(siteId).set(page, { merge: true });

  const jobRef = await db.collection('jobs').add({
    ownerUid: OWNER_UID,
    type: 'site_refiner',
    status: 'queued',
    plan: {
      flowId: 'site_refiner-flow',
      steps: STEPS.map((step) => step.name),
      params: {
        siteId,
        siteTitle: jobTitle,
        tenantId: OWNER_UID,
      },
    },
    steps: [],
    createdAt: FieldValue.serverTimestamp(),
    updatedAt: FieldValue.serverTimestamp(),
  });

  const stepEntries = STEPS.map((step, index) => ({
    name: step.name,
    status: 'done' as const,
    result: step.result,
    timestamp: Date.now() + index * 1000,
  }));

  await jobRef.update({
    status: 'done',
    steps: stepEntries,
    result: {
      artifacts: {
        refinedSnapshot: {
          ...page,
          blocks: page.blocks.map((block) =>
            block.type === 'hero'
              ? {
                  ...block,
                  data: {
                    ...block.data,
                    headline: 'Refiner Draft Ready',
                    description: 'Generated by smoke test to validate UI surfaces.',
                  },
                }
              : block,
          ),
        },
        refinedHtml: `<section><h1>${jobTitle}</h1><p>Smoke draft completed.</p></section>`,
      },
    },
    updatedAt: FieldValue.serverTimestamp(),
  });

  const now = new Date().toISOString();
  await db.collection('sites').doc(siteId).set(
    {
      refinerStatus: 'review',
      lastRefinedAt: now,
      lastRefinerJobId: jobRef.id,
    },
    { merge: true },
  );

  return { jobId: jobRef.id, siteId };
}

async function assertPropagation(jobId: string, siteId: string) {
  const db = getFirestore();
  const jobSnap = await db.collection('jobs').doc(jobId).get();
  const jobData = jobSnap.data();
  assert.ok(jobData, 'Job should exist after creation');
  assert.equal(jobData?.status, 'done', 'Smoke job should complete');
  assert.ok(jobData?.result?.artifacts?.refinedSnapshot, 'Refiner artifacts should contain a snapshot');
  assert.ok(
    jobData?.steps?.length === STEPS.length,
    'Refiner job should record all planned steps for Admin timeline',
  );

  const siteSnap = await db.collection('sites').doc(siteId).get();
  const siteData = siteSnap.data();
  assert.ok(siteData, 'Site should exist for smoke job');
  assert.equal(siteData?.refinerStatus, 'review', 'Site should reflect refiner review status');
  assert.equal(siteData?.lastRefinerJobId, jobId, 'Site metadata should point to smoke job id');

  console.log('✨ Smoke job complete');
  console.log(`   Job ${jobId} status: ${jobData?.status}, steps: ${jobData?.steps?.length}`);
  console.log(`   Site ${siteId} status: ${siteData?.refinerStatus}, lastRefinedAt: ${siteData?.lastRefinedAt}`);
}

async function run() {
  initAdmin();
  const { jobId, siteId } = await queueRefinerJob();
  await assertPropagation(jobId, siteId);
}

run().catch((error) => {
  console.error('❌ Refiner smoke test failed', error);
  process.exit(1);
});
