import type { BlockTemplate } from "../types"

const defaultTextEffects = {
  shadow: { enabled: false, offsetX: 2, offsetY: 2, blur: 4, color: "rgba(0,0,0,0.5)" },
  outline: { enabled: false, width: 2, color: "#000000" },
}

// ============================================
// HERO BLOCKS (4)
// ============================================

export const HERO_BLOCKS: BlockTemplate[] = [
  {
    id: "hero-modern-video",
    name: "Modern Hero with Video",
    description: "Full-width hero with video background and overlay",
    category: "hero",
    width: "full",
    minHeight: 600,
    tags: ["hero", "video", "cta", "landing"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [
      {
        id: "hero-video-bg",
        type: "image",
        position: { x: 0, y: 0 },
        width: 1200,
        height: 600,
        imageUrl: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&h=600&fit=crop",
        opacity: 0.7,
        rotation: 0,
        locked: false,
        zIndex: 1,
        borderRadius: 0,
        objectFit: "cover",
      },
      {
        id: "hero-overlay",
        type: "rectangle",
        position: { x: 0, y: 0 },
        width: 1200,
        height: 600,
        fill: "rgba(0, 0, 0, 0.4)",
        stroke: "transparent",
        strokeWidth: 0,
        opacity: 1,
        rotation: 0,
        locked: false,
        zIndex: 2,
      },
      {
        id: "hero-title",
        type: "custom",
        content: "Find Your Dream Home",
        position: { x: 100, y: 200 },
        fontFamily: "Geist, sans-serif",
        fontSize: 64,
        fontWeight: 700,
        color: "#ffffff",
        backgroundColor: "transparent",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1.2,
        locked: false,
        zIndex: 3,
        effects: defaultTextEffects,
      },
      {
        id: "hero-subtitle",
        type: "custom",
        content: "Browse luxury properties in your area",
        position: { x: 100, y: 300 },
        fontFamily: "Geist, sans-serif",
        fontSize: 24,
        fontWeight: 400,
        color: "#e0e0e0",
        backgroundColor: "transparent",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1.4,
        locked: false,
        zIndex: 3,
        effects: defaultTextEffects,
      },
    ],
    dataBindings: [],
  },
  {
    id: "hero-simple-image",
    name: "Simple Hero with Image",
    description: "Clean hero with background image and content overlay",
    category: "hero",
    width: "full",
    minHeight: 500,
    tags: ["hero", "image", "simple"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [
      {
        id: "hero-img",
        type: "image",
        position: { x: 0, y: 0 },
        width: 1200,
        height: 500,
        imageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200&h=500&fit=crop",
        opacity: 1,
        rotation: 0,
        locked: false,
        zIndex: 1,
        borderRadius: 0,
        objectFit: "cover",
      },
      {
        id: "hero-text",
        type: "custom",
        content: "Welcome to Your Real Estate Journey",
        position: { x: 100, y: 220 },
        fontFamily: "Geist, sans-serif",
        fontSize: 48,
        fontWeight: 700,
        color: "#1a1a1a",
        backgroundColor: "rgba(255, 255, 255, 0.8)",
        showBackground: true,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1.3,
        locked: false,
        zIndex: 2,
        effects: defaultTextEffects,
      },
    ],
    dataBindings: [],
  },
  {
    id: "hero-overlay-cta",
    name: "Overlay Hero with CTA",
    description: "Hero with content overlay and call-to-action button",
    category: "hero",
    width: "full",
    minHeight: 550,
    tags: ["hero", "cta", "conversion"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [
      {
        id: "hero-bg-overlay",
        type: "image",
        position: { x: 0, y: 0 },
        width: 1200,
        height: 550,
        imageUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&h=550&fit=crop",
        opacity: 1,
        rotation: 0,
        locked: false,
        zIndex: 1,
        borderRadius: 0,
        objectFit: "cover",
      },
      {
        id: "hero-gradient-overlay",
        type: "rectangle",
        position: { x: 0, y: 0 },
        width: 1200,
        height: 550,
        fill: "rgba(0, 0, 0, 0.5)",
        stroke: "transparent",
        strokeWidth: 0,
        opacity: 1,
        rotation: 0,
        locked: false,
        zIndex: 2,
      },
      {
        id: "hero-content",
        type: "custom",
        content: "Expert Real Estate Solutions",
        position: { x: 150, y: 200 },
        fontFamily: "Geist, sans-serif",
        fontSize: 56,
        fontWeight: 700,
        color: "#ffffff",
        backgroundColor: "transparent",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1.2,
        locked: false,
        zIndex: 3,
        effects: defaultTextEffects,
      },
      {
        id: "hero-cta-btn",
        type: "rectangle",
        position: { x: 150, y: 320 },
        width: 200,
        height: 60,
        fill: "#2563eb",
        stroke: "transparent",
        strokeWidth: 0,
        opacity: 1,
        rotation: 0,
        locked: false,
        zIndex: 3,
        borderRadius: 8,
      },
      {
        id: "hero-btn-text",
        type: "custom",
        content: "Start Your Search",
        position: { x: 165, y: 335 },
        fontFamily: "Geist, sans-serif",
        fontSize: 18,
        fontWeight: 600,
        color: "#ffffff",
        backgroundColor: "transparent",
        showBackground: false,
        textAlign: "center",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 4,
        effects: defaultTextEffects,
      },
    ],
    dataBindings: [],
  },
  {
    id: "hero-search",
    name: "Search Hero Block",
    description: "Hero with integrated property search form",
    category: "hero",
    width: "full",
    minHeight: 500,
    tags: ["hero", "search", "form", "conversion"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [
      {
        id: "search-hero-bg",
        type: "image",
        position: { x: 0, y: 0 },
        width: 1200,
        height: 500,
        imageUrl: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1200&h=500&fit=crop",
        opacity: 1,
        rotation: 0,
        locked: false,
        zIndex: 1,
        borderRadius: 0,
        objectFit: "cover",
      },
      {
        id: "search-overlay",
        type: "rectangle",
        position: { x: 0, y: 0 },
        width: 1200,
        height: 500,
        fill: "rgba(0, 0, 0, 0.3)",
        stroke: "transparent",
        strokeWidth: 0,
        opacity: 1,
        rotation: 0,
        locked: false,
        zIndex: 2,
      },
      {
        id: "search-title",
        type: "custom",
        content: "Find Properties That Match Your Style",
        position: { x: 50, y: 80 },
        fontFamily: "Geist, sans-serif",
        fontSize: 48,
        fontWeight: 700,
        color: "#ffffff",
        backgroundColor: "transparent",
        showBackground: false,
        textAlign: "center",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1.2,
        locked: false,
        zIndex: 3,
        effects: defaultTextEffects,
      },
      {
        id: "search-form-bg",
        type: "rectangle",
        position: { x: 50, y: 200 },
        width: 1100,
        height: 200,
        fill: "#ffffff",
        stroke: "transparent",
        strokeWidth: 0,
        opacity: 0.95,
        rotation: 0,
        locked: false,
        zIndex: 3,
        borderRadius: 12,
      },
    ],
    dataBindings: [],
  },
]

// ============================================
// PROPERTY GRID BLOCKS (5)
// ============================================

export const PROPERTY_GRID_BLOCKS: BlockTemplate[] = [
  {
    id: "property-grid-3col",
    name: "Property Grid (3 Columns)",
    description: "3-column property listing grid",
    category: "grid",
    width: "full",
    minHeight: 800,
    tags: ["grid", "properties", "listings"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [
      {
        id: "grid-title",
        type: "custom",
        content: "Featured Properties",
        position: { x: 50, y: 30 },
        fontFamily: "Geist, sans-serif",
        fontSize: 42,
        fontWeight: 700,
        color: "#1a1a1a",
        backgroundColor: "transparent",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 1,
        effects: defaultTextEffects,
      },
      // Property cards would be repeated 3 times in actual implementation
      {
        id: "property-card-1-img",
        type: "image",
        position: { x: 50, y: 120 },
        width: 350,
        height: 250,
        imageUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=350&h=250&fit=crop",
        opacity: 1,
        rotation: 0,
        locked: false,
        zIndex: 1,
        borderRadius: 8,
        objectFit: "cover",
      },
      {
        id: "property-card-1-price",
        type: "custom",
        content: "$850,000",
        position: { x: 50, y: 385 },
        fontFamily: "Geist, sans-serif",
        fontSize: 28,
        fontWeight: 700,
        color: "#1a1a1a",
        backgroundColor: "transparent",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 1,
        effects: defaultTextEffects,
      },
    ],
    dataBindings: [
      {
        propertyPath: "properties",
        elementId: "property-card-1-img",
        type: "repeater",
      },
    ],
  },
  {
    id: "property-grid-4col",
    name: "Property Grid (4 Columns)",
    description: "4-column compact property grid",
    category: "grid",
    width: "full",
    minHeight: 700,
    tags: ["grid", "properties", "compact"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [
      {
        id: "grid4-title",
        type: "custom",
        content: "All Available Properties",
        position: { x: 50, y: 20 },
        fontFamily: "Geist, sans-serif",
        fontSize: 36,
        fontWeight: 700,
        color: "#1a1a1a",
        backgroundColor: "transparent",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 1,
        effects: defaultTextEffects,
      },
    ],
    dataBindings: [
      {
        propertyPath: "properties",
        elementId: "grid4-title",
        type: "repeater",
      },
    ],
  },
  {
    id: "featured-carousel",
    name: "Featured Properties Carousel",
    description: "Carousel slider for featured properties",
    category: "grid",
    width: "full",
    minHeight: 450,
    tags: ["carousel", "featured", "properties"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [
      {
        id: "carousel-title",
        type: "custom",
        content: "Featured This Month",
        position: { x: 50, y: 20 },
        fontFamily: "Geist, sans-serif",
        fontSize: 36,
        fontWeight: 700,
        color: "#1a1a1a",
        backgroundColor: "transparent",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 1,
        effects: defaultTextEffects,
      },
    ],
    dataBindings: [],
  },
  {
    id: "premium-grid-sidebar",
    name: "Premium Grid with Sidebar",
    description: "Premium properties grid with filters sidebar",
    category: "grid",
    width: "full",
    minHeight: 600,
    tags: ["grid", "premium", "filters"],
    responsive: false,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
  {
    id: "map-grid-hybrid",
    name: "Map & Grid Hybrid View",
    description: "Map on left, property grid on right",
    category: "grid",
    width: "full",
    minHeight: 700,
    tags: ["map", "grid", "hybrid"],
    responsive: false,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
]

// ============================================
// PROPERTY CARD BLOCKS (6)
// ============================================

export const PROPERTY_CARD_BLOCKS: BlockTemplate[] = [
  {
    id: "card-minimal",
    name: "Minimal Property Card",
    description: "Minimal card with image, price, and location",
    category: "card",
    width: "third",
    minHeight: 320,
    tags: ["card", "minimal", "simple"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [
      {
        id: "card-min-img",
        type: "image",
        position: { x: 0, y: 0 },
        width: 350,
        height: 200,
        imageUrl: "https://images.unsplash.com/photo-1570129477492-45a003537e1f?w=350&h=200&fit=crop",
        opacity: 1,
        rotation: 0,
        locked: false,
        zIndex: 1,
        borderRadius: 8,
        objectFit: "cover",
      },
      {
        id: "card-min-price",
        type: "custom",
        content: "$650,000",
        position: { x: 15, y: 220 },
        fontFamily: "Geist, sans-serif",
        fontSize: 24,
        fontWeight: 700,
        color: "#1a1a1a",
        backgroundColor: "transparent",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 2,
        effects: defaultTextEffects,
      },
      {
        id: "card-min-address",
        type: "custom",
        content: "123 Main Street, San Francisco, CA",
        position: { x: 15, y: 260 },
        fontFamily: "Geist, sans-serif",
        fontSize: 14,
        fontWeight: 400,
        color: "#666666",
        backgroundColor: "transparent",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1.4,
        locked: false,
        zIndex: 2,
        effects: defaultTextEffects,
      },
    ],
    dataBindings: [
      { propertyPath: "property.price", elementId: "card-min-price", type: "text" },
      { propertyPath: "property.address", elementId: "card-min-address", type: "text" },
    ],
  },
  {
    id: "card-detailed",
    name: "Detailed Property Card",
    description: "Card with beds, baths, sqft info",
    category: "card",
    width: "third",
    minHeight: 380,
    tags: ["card", "detailed", "info"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
  {
    id: "card-hover-reveal",
    name: "Hover Reveal Card",
    description: "Description reveals on hover",
    category: "card",
    width: "half",
    minHeight: 320,
    tags: ["card", "hover", "interactive"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
  {
    id: "card-glassmorphism",
    name: "Glassmorphism Card",
    description: "Modern glassmorphism style property card",
    category: "card",
    width: "third",
    minHeight: 340,
    tags: ["card", "modern", "glassmorphism"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
  {
    id: "card-agent-overlay",
    name: "Agent Overlay Card",
    description: "Property card with agent info overlay",
    category: "card",
    width: "third",
    minHeight: 350,
    tags: ["card", "agent", "overlay"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
  {
    id: "card-open-house",
    name: "Open House Special Card",
    description: "Property card highlighting open house event",
    category: "card",
    width: "third",
    minHeight: 360,
    tags: ["card", "event", "open-house"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
]

// ============================================
// FORM BLOCKS (4)
// ============================================

export const FORM_BLOCKS: BlockTemplate[] = [
  {
    id: "form-contact",
    name: "Contact Form",
    description: "General contact form block",
    category: "form",
    width: "container",
    minHeight: 400,
    tags: ["form", "contact", "lead"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [
      {
        id: "form-title",
        type: "custom",
        content: "Get in Touch",
        position: { x: 50, y: 30 },
        fontFamily: "Geist, sans-serif",
        fontSize: 36,
        fontWeight: 700,
        color: "#1a1a1a",
        backgroundColor: "transparent",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 1,
        effects: defaultTextEffects,
      },
    ],
    dataBindings: [],
  },
  {
    id: "form-lead-capture",
    name: "Lead Capture Form",
    description: "Form for property interest capture",
    category: "form",
    width: "container",
    minHeight: 350,
    tags: ["form", "lead", "property"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
  {
    id: "form-schedule-tour",
    name: "Schedule Tour Form",
    description: "Form to schedule property tours",
    category: "form",
    width: "container",
    minHeight: 380,
    tags: ["form", "tour", "scheduling"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
  {
    id: "form-property-inquiry",
    name: "Property Inquiry Form",
    description: "Detailed property inquiry form",
    category: "form",
    width: "container",
    minHeight: 420,
    tags: ["form", "inquiry", "property"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
]

// ============================================
// AGENT/TEAM BLOCKS (4)
// ============================================

export const AGENT_BLOCKS: BlockTemplate[] = [
  {
    id: "agent-team-grid",
    name: "Agent Team Grid",
    description: "Team member grid layout",
    category: "agent",
    width: "full",
    minHeight: 600,
    tags: ["agent", "team", "grid"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
  {
    id: "agent-spotlight",
    name: "Agent Spotlight Card",
    description: "Featured agent profile card",
    category: "agent",
    width: "container",
    minHeight: 500,
    tags: ["agent", "spotlight", "featured"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
  {
    id: "agent-testimonials-carousel",
    name: "Agent Testimonials Carousel",
    description: "Carousel of agent reviews/testimonials",
    category: "agent",
    width: "full",
    minHeight: 400,
    tags: ["testimonials", "carousel", "reviews"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
  {
    id: "agent-of-month",
    name: "Agent of the Month",
    description: "Showcase monthly featured agent",
    category: "agent",
    width: "container",
    minHeight: 450,
    tags: ["agent", "feature", "monthly"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
]

// ============================================
// INFORMATION BLOCKS (8)
// ============================================

export const INFO_BLOCKS: BlockTemplate[] = [
  {
    id: "info-about",
    name: "About Agency Section",
    description: "Agency description and mission",
    category: "info",
    width: "full",
    minHeight: 400,
    tags: ["about", "company", "info"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
  {
    id: "info-why-choose",
    name: "Why Choose Us",
    description: "Benefits with icons section",
    category: "info",
    width: "full",
    minHeight: 350,
    tags: ["benefits", "features", "info"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
  {
    id: "info-services-3col",
    name: "Services (3 Column)",
    description: "Service offerings in 3 columns",
    category: "info",
    width: "full",
    minHeight: 380,
    tags: ["services", "features", "3col"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
  {
    id: "info-services-4col",
    name: "Services (4 Column)",
    description: "Service offerings in 4 columns",
    category: "info",
    width: "full",
    minHeight: 350,
    tags: ["services", "features", "4col"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
  {
    id: "info-testimonials",
    name: "Testimonials Carousel",
    description: "Client testimonials in carousel",
    category: "info",
    width: "full",
    minHeight: 300,
    tags: ["testimonials", "reviews", "social-proof"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
  {
    id: "info-stats",
    name: "Statistics Showcase",
    description: "Properties sold, happy clients, etc.",
    category: "info",
    width: "full",
    minHeight: 280,
    tags: ["stats", "metrics", "numbers"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
  {
    id: "info-cta-banner",
    name: "Call-to-Action Banner",
    description: "Large CTA banner section",
    category: "info",
    width: "full",
    minHeight: 200,
    tags: ["cta", "banner", "conversion"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
  {
    id: "info-faq",
    name: "FAQ Accordion",
    description: "Frequently asked questions accordion",
    category: "info",
    width: "container",
    minHeight: 450,
    tags: ["faq", "accordion", "questions"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
]

// ============================================
// HEADER/FOOTER BLOCKS (4)
// ============================================

export const HEADER_FOOTER_BLOCKS: BlockTemplate[] = [
  {
    id: "header-sticky",
    name: "Sticky Header Navigation",
    description: "Sticky navigation header",
    category: "header",
    width: "full",
    minHeight: 80,
    tags: ["header", "navigation", "sticky"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
  {
    id: "header-mobile-menu",
    name: "Mobile Hamburger Menu",
    description: "Mobile-friendly hamburger menu",
    category: "header",
    width: "full",
    minHeight: 60,
    tags: ["header", "mobile", "menu"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
  {
    id: "footer-standard",
    name: "Standard Footer",
    description: "Standard footer with links",
    category: "footer",
    width: "full",
    minHeight: 300,
    tags: ["footer", "links", "standard"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
  {
    id: "footer-modern",
    name: "Modern Footer",
    description: "Modern footer with newsletter and social",
    category: "footer",
    width: "full",
    minHeight: 350,
    tags: ["footer", "newsletter", "modern"],
    responsive: true,
    createdAt: new Date().toISOString(),
    elements: [],
    dataBindings: [],
  },
]

// ============================================
// EXPORT ALL BLOCKS
// ============================================

export const ALL_REAL_ESTATE_BLOCKS: BlockTemplate[] = [
  ...HERO_BLOCKS,
  ...PROPERTY_GRID_BLOCKS,
  ...PROPERTY_CARD_BLOCKS,
  ...FORM_BLOCKS,
  ...AGENT_BLOCKS,
  ...INFO_BLOCKS,
  ...HEADER_FOOTER_BLOCKS,
]

// Organize by category for quick lookup
export const BLOCKS_BY_CATEGORY = {
  hero: HERO_BLOCKS,
  grid: PROPERTY_GRID_BLOCKS,
  card: PROPERTY_CARD_BLOCKS,
  form: FORM_BLOCKS,
  agent: AGENT_BLOCKS,
  info: INFO_BLOCKS,
  header: [HEADER_FOOTER_BLOCKS[0], HEADER_FOOTER_BLOCKS[1]],
  footer: [HEADER_FOOTER_BLOCKS[2], HEADER_FOOTER_BLOCKS[3]],
}
